package pojo;
// Generated Oct 10, 2022 10:46:24 AM by Hibernate Tools 4.3.1


import DAO.DAOLogin;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.faces.bean.ManagedBean;

/**
 * Admins generated by hbm2java
 */

@ManagedBean
public class Admins  implements java.io.Serializable {


     private Integer idAdmin;
     private String adminName;
     private String email;
     private String password;
     private Set orderses = new HashSet(0);

    public Admins() {
    }

	
    public Admins(String adminName, String email, String password) {
        this.adminName = adminName;
        this.email = email;
        this.password = password;
    }
    public Admins(String adminName, String email, String password, Set orderses) {
       this.adminName = adminName;
       this.email = email;
       this.password = password;
       this.orderses = orderses;
    }
   
    public Integer getIdAdmin() {
        return this.idAdmin;
    }
    
    public void setIdAdmin(Integer idAdmin) {
        this.idAdmin = idAdmin;
    }
    public String getAdminName() {
        return this.adminName;
    }
    
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }


    public String loginValidation(){
        DAOLogin uDao = new DAOLogin();
        List<Admins> ad = uDao.getBy(email, password);
        if (ad != null){
            email = ad.get(0).email;
            password = ad.get(0).password;
            return "homepage";
        }
        return "login_failed";
    }
    
    public String save_admin() {
        DAOLogin add = new DAOLogin();
        return add.add_admin(this);
    }

}


