package pojo;
// Generated Oct 10, 2022 10:46:24 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private Integer idOrder;
     private Admins admins;
     private Albums albums;
     private Integer amount;
     private Integer totalPrice;
     private Date orderDate;

    public Orders() {
    }

    public Orders(Admins admins, Albums albums, Integer amount, Integer totalPrice, Date orderDate) {
       this.admins = admins;
       this.albums = albums;
       this.amount = amount;
       this.totalPrice = totalPrice;
       this.orderDate = orderDate;
    }
   
    public Integer getIdOrder() {
        return this.idOrder;
    }
    
    public void setIdOrder(Integer idOrder) {
        this.idOrder = idOrder;
    }
    public Admins getAdmins() {
        return this.admins;
    }
    
    public void setAdmins(Admins admins) {
        this.admins = admins;
    }
    public Albums getAlbums() {
        return this.albums;
    }
    
    public void setAlbums(Albums albums) {
        this.albums = albums;
    }
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
    public Integer getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Integer totalPrice) {
        this.totalPrice = totalPrice;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }




}


